### PR TITLE
Update Kotlin stuff

### PR DESCRIPTION
**Pull request by camdenorrb**
Might want to double check that millisecond change I did, but other than that should be fine.

### CODE REVIEW

**Comment by camdenorrb** [comment]
#14

**Comment by okkero** [comment]
Thanks. I will review this later today

**Comment by camdenorrb** [comment]
2 days later.... :P

**Comment by okkero** [comment]
Yes, sorry about that. I got caught up in some stuff. I guess I underestimated my schedule. Haven't had a single free evening this entire week. Today is not gonna be different. I might get to do this tomorrow morning :)

**Comment by camdenorrb** [comment]
Awh alright, hope it loosens up eventually

**Comment by DevSrSouza** [comment]
Waiting for the merge, I think fix this bug

**Comment by okkero** [comment]
sorry for the long delay

**Pull request merged**
